// The published gateway package is the only source of truth for benefit data
// shapes. This module is intentionally only a re-export boundary.
export {
  StrictCoarseProfileSchema as StrictUserProfileSchema,
  UserProfileSchema,
  BenefitSummarySchema,
  BenefitCandidateV2Schema,
  CandidateAssessmentSchema,
  RankingSchema,
  ScoreBreakdownItemSchema,
  BenefitDetailSchema,
  GetBenefitDetailResponseSchema,
  ChecklistResponseSchema,
  ChecklistItemSchema,
  ApplicationGuideResponseSchema,
  ApplicationStepSchema,
  UpcomingDeadlineSummarySchema,
  UpcomingDeadlinesResponseSchema,
  BenefitSearchResponseSchema,
  ListPersonasResponseSchema,
  RecommendationPersonaSchema,
  BenefitCategorySchema,
  RecommendationWeightsSchema,
  DataStatusSchema,
  VerifiedLinkSchema,
  StableMcpErrorSchema,
  HostileDisplayTextFixtureSchema,
  normalizeQuery,
} from "@mcp-gen-ui/schema";

export type {
  StrictCoarseProfile as UserProfile,
  BenefitSummary,
  BenefitCandidateV2,
  CandidateAssessment,
  Ranking,
  ScoreBreakdownItem,
  BenefitDetail,
  GetBenefitDetailResponse,
  ChecklistResponse,
  ApplicationGuideResponse,
  RecommendationPersona,
  BenefitCategory,
  BenefitSearchResponse,
  UpcomingDeadlinesResponse,
  ListPersonasResponse,
  RecommendationWeights,
  DataStatus,
  VerifiedLink,
  StableMcpError,
} from "@mcp-gen-ui/schema";
